# Generated by Django 5.2.10 on 2026-01-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('hq_country', models.CharField(blank=True, max_length=100, null=True)),
                ('org_type', models.CharField(blank=True, help_text='public, private, gov, edu, nonprofit', max_length=50, null=True)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('domain_confidence_score', models.FloatField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('work_website', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('owned_by', models.CharField(blank=True, help_text='Owner name or email', max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('pdl_total_funding_raised', models.FloatField(blank=True, null=True)),
                ('pdl_latest_funding_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('pdl_last_funding_date', models.DateTimeField(blank=True, null=True)),
                ('pdl_number_funding_rounds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('signup_date', models.DateTimeField(blank=True, null=True)),
                ('session_count', models.IntegerField(blank=True, null=True)),
                ('is_free_email', models.BooleanField(default=False)),
                ('is_candidate_enterprise', models.BooleanField(default=False)),
                ('lead_score', models.IntegerField(default=0)),
                ('lead_stage', models.CharField(blank=True, choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('very_high', 'Very High Priority'), ('enterprise', 'Enterprise Target')], max_length=50, null=True)),
                ('hierarchical_level', models.CharField(blank=True, choices=[('low', 'Low Level'), ('medium', 'Medium Level'), ('high', 'High Level'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('campaign_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('email_status', models.CharField(choices=[('active', 'Active'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=50)),
                ('crm_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_date', models.DateTimeField(blank=True, null=True)),
                ('pdl_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pdl_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pdl_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdl_linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pdl_job_last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.company')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
