# Generated by Django 5.2.10 on 2026-02-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.company')),
            ],
            options={
                'verbose_name': 'Company Note',
                'verbose_name_plural': 'Company Notes',
                'db_table': 'company_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
